version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: invoicing
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: invoicing

	invoicing:
		build: .
		image: chamaconekt/invoicing
		links:
		- postgres
		container_name: invoicing
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- invoicing
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/invoicing-nginx/nginx.conf
		depends_on:
			- invoicing
		ports:
			- 80:80
		volumes_from:
			- invoicing

volumes:
	invoicing-static-files:
		driver:local